a = int(input("Value of a:"))
b = int(input("Value of b:"))
c = int(input("Value of c:"))
num = (-b + (b**2 - 4*a*c) ** 0.5)/(2*a)
num1 = (-b - (b**2 - 4*a*c) ** 0.5)/(2*a)
print("The roots are",num,"and",num1)